version: "3"

services:
  database:
    build:
      context: .
      dockerfile: "./bin/${POSTGRES12}/Dockerfile"
    container_name: "${PROJECT_NAME}-${POSTGRES12}"
    restart: "always"
    ports:
      - "127.0.0.1:${HOST_MACHINE_POSTGRES_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  db:
